version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: scheduling_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-scheduling_db}
      DB_USERNAME: ${DB_USERNAME:-scheduling_user}
      DB_PASSWORD: ${DB_PASSWORD:-scheduling_pass}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_pass}
      JWT_SECRET: ${JWT_SECRET:-your_strong_32char_secret_key_here_12345678}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600}
    depends_on:
      - mysql
    networks:
      - scheduling_net

  web:
    image: nginx:alpine
    container_name: scheduling_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - scheduling_net

  mysql:
    image: mysql:8.0
    container_name: scheduling_mysql
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_pass}
      MYSQL_DATABASE: ${DB_DATABASE:-scheduling_db}
      MYSQL_USER: ${DB_USERNAME:-scheduling_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-scheduling_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - scheduling_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: scheduling_pma
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - scheduling_net

networks:
  scheduling_net:
    driver: bridge

volumes:
  mysql_