name: CI/CD with PHP 8.4 & MySQL 8.0

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Test with PHP 8.4 & MySQL 8.0

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: scheduling_db
          MYSQL_USER: scheduling_user
          MYSQL_PASSWORD: scheduling_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --default-authentication-plugin=mysql_native_password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, mbstring, dom, gd, zip, bcmath, opcache
          ini-values: post_max_size=100M, upload_max_filesize=100M, date.timezone=UTC

      - name: Copy Environment
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      - name: Patch Phinx Config for CI
        run: |
          sed -i "s/\$_ENV\['DB_HOST'\] ?? 'localhost'/'127.0.0.1'/g" phinx.php
          sed -i "s/\$_ENV\['DB_DATABASE'\]/'scheduling_db'/g" phinx.php
          sed -i "s/\$_ENV\['DB_USERNAME'\]/'scheduling_user'/g" phinx.php
          sed -i "s/\$_ENV\['DB_PASSWORD'\]/'scheduling_pass'/g" phinx.php

      - name: Run Phinx Migrations
        run: php vendor/bin/phinx migrate

      - name: Run PHPStan (PHP 8.4 Compatible)
        run: |
          composer require --dev phpstan/phpstan:^2.0
          vendor/bin/phpstan analyse src/

      - name: Run PHPUnit Tests
        run: |
          mkdir -p tests/Unit
          cat > tests/Unit/DummyTest.php << 'EOT'
  <?php
  use PHPUnit\Framework\TestCase;
  class DummyTest extends TestCase {
  public function testTrueIsTrue() {
  \$this->assertTrue(true);
}
}
  EOT
  vendor/bin/phpunit --bootstrap vendor/autoload.php tests/

deploy:
  needs: ci
  runs-on: ubuntu-latest
  name: Deploy to Production
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd /var/www/scheduling-system
          git pull origin main
          cp .env.prod .env
          docker-compose down
          docker-compose up -d --build --force-recreate
          docker-compose exec app composer install --optimize-autoloader --no-dev
          docker-compose exec app php vendor/bin/phinx migrate
          echo "✅ Deployed on $(date)" >> deploy.log